import type { TranslationLanguage } from './data/translationLoaders';

export interface MandarinSpeechCopy {
  audioUnavailable: string;
  noMandarinVoice: string;
  customAudioFallbackUnavailable: string;
  usingBrowserFallbackAudio: string;
  usingBrowserAudio: string;
  audioCouldNotPlay: (error: string) => string;
}

export interface UiCopy {
  htmlLang: string;
  direction: 'ltr' | 'rtl';
  allHsk: string;
  classicMaps: string;
  allOverview: string;
  tileMap: (label: string) => string;
  words: (count: number) => string;
  newWords: (count: number) => string;
  shown: (visible: number, total: number) => string;
  filters: Record<'all' | 'learning' | 'know' | 'unmarked', string>;
  promptModes: Record<'chinese' | 'translation', string>;
  searchLabel: string;
  searchPlaceholder: string;
  reset: string;
  known: string;
  review: string;
  unmarked: string;
  progressSummary: string;
  mapControls: string;
  menuLabel: string;
  hskLevel: string;
  progressFilter: string;
  flashcardPromptSide: string;
  translationLanguage: string;
  showTranslationsIn: (language: string) => string;
  allHskOverview: string;
  levelProgress: (level: number) => string;
  matchingWords: (level: number) => string;
  wordMap: (label: string) => string;
  scrollableWordMap: (label: string) => string;
  canvasWordMap: (label: string) => string;
  wordList: (label: string) => string;
  wordRange: (label: string, start: number, end: number) => string;
  levelCardCount: (visible: number, total: number) => string;
  levelKnown: (count: number) => string;
  levelLearning: (count: number) => string;
  levelUnmarked: (count: number) => string;
  noMatchesInLevel: string;
  noWordsMatch: string;
  tryDifferentSearch: string;
  closeDetails: string;
  hskWord: (level: number) => string;
  revealChinese: string;
  revealAnswer: string;
  hideAnswer: string;
  unlockWriting: string;
  unlockExample: string;
  exampleSentence: string;
  showPinyin: string;
  hidePinyin: string;
  playAudio: string;
  reviewAgain: string;
  iKnowThis: string;
  clear: string;
  writing: {
    strokeOrder: string;
    writingMode: string;
    watch: string;
    practice: string;
    recall: string;
    writePrompt: string;
    replay: string;
    reset: string;
    hint: string;
    writeCharacter: (character: string) => string;
    strokeDataError: string;
    tryStrokeAgain: string;
    goodStroke: string;
    characterComplete: (character: string) => string;
    wordComplete: string;
    strokeOrderAnimation: (hanzi: string) => string;
    animatedStrokeOrder: (character: string) => string;
    characterStep: (current: number, total: number) => string;
    practiceWriting: (character: string) => string;
    practiceCharacter: string;
    strokeProgress: (current: number | string, total: number | string) => string;
    done: (count: number) => string;
    mistakes: (count: number) => string;
    characters: (completed: number, total: number) => string;
  };
  resetDialog: {
    kicker: string;
    title: string;
    description: (label: string) => string;
    summary: (label: string) => string;
    known: string;
    review: string;
    wordsAffected: string;
    note: string;
    keepProgress: string;
    resetProgress: string;
  };
  speech: MandarinSpeechCopy;
}

const UI_COPY: Record<TranslationLanguage, UiCopy> = {
  en: {
    htmlLang: 'en',
    direction: 'ltr',
    allHsk: 'All HSK',
    classicMaps: 'Classic HSK 1-6 word maps',
    allOverview: 'All HSK Level Overview',
    tileMap: (label) => `${label} Tile Map`,
    words: (count) => `${count.toLocaleString('en')} words`,
    newWords: (count) => `${count.toLocaleString('en')} new words`,
    shown: (visible, total) => `${visible.toLocaleString('en')} / ${total.toLocaleString('en')} shown`,
    filters: { all: 'All', learning: 'Review', know: 'Known', unmarked: 'Unmarked' },
    promptModes: { chinese: 'Chinese first', translation: 'Translation first' },
    searchLabel: 'Search',
    searchPlaceholder: 'Chinese, pinyin, or translation',
    reset: 'Reset',
    known: 'Known',
    review: 'Review',
    unmarked: 'Unmarked',
    progressSummary: 'Progress summary',
    mapControls: 'Map controls',
    menuLabel: 'Menu',
    hskLevel: 'HSK level',
    progressFilter: 'Progress filter',
    flashcardPromptSide: 'Flashcard prompt side',
    translationLanguage: 'Translation language',
    showTranslationsIn: (language) => `Show translations in ${language}`,
    allHskOverview: 'All HSK level overview',
    levelProgress: (level) => `HSK ${level} progress`,
    matchingWords: (level) => `HSK ${level} matching words`,
    wordMap: (label) => `${label} word map`,
    scrollableWordMap: (label) => `${label} scrollable word map`,
    canvasWordMap: (label) => `${label} canvas word map`,
    wordList: (label) => `${label} word list`,
    wordRange: (label, start, end) => `${label} words ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('en')} / ${total.toLocaleString('en')} shown`,
    levelKnown: (count) => `${count.toLocaleString('en')} know`,
    levelLearning: (count) => `${count.toLocaleString('en')} learning`,
    levelUnmarked: (count) => `${count.toLocaleString('en')} unmarked`,
    noMatchesInLevel: 'No matches in this level.',
    noWordsMatch: 'No words match this view.',
    tryDifferentSearch: 'Try a different search or progress filter.',
    closeDetails: 'Close details',
    hskWord: (level) => `HSK ${level} Word`,
    revealChinese: 'Reveal Chinese',
    revealAnswer: 'Reveal answer',
    hideAnswer: 'Hide answer',
    unlockWriting: 'Reveal Chinese to unlock writing practice',
    unlockExample: 'Reveal Chinese to unlock the example',
    exampleSentence: 'Example sentence',
    showPinyin: 'Show pinyin',
    hidePinyin: 'Hide pinyin',
    playAudio: 'Play audio',
    reviewAgain: 'Review Again',
    iKnowThis: 'I Know This',
    clear: 'Clear',
    writing: {
      strokeOrder: 'Stroke order',
      writingMode: 'Writing mode',
      watch: 'Watch',
      practice: 'Practice',
      recall: 'Recall',
      writePrompt: 'Write',
      replay: 'Replay',
      reset: 'Reset',
      hint: 'Hint',
      writeCharacter: (character) => `Write ${character}`,
      strokeDataError: 'Stroke data could not be loaded for this character.',
      tryStrokeAgain: 'Try that stroke again',
      goodStroke: 'Good stroke',
      characterComplete: (character) => `${character} complete`,
      wordComplete: 'Word complete',
      strokeOrderAnimation: (hanzi) => `Stroke order animation for ${hanzi}`,
      animatedStrokeOrder: (character) => `Animated stroke order for ${character}`,
      characterStep: (current, total) => `Character ${current} / ${total}`,
      practiceWriting: (character) => `Practice writing ${character}`,
      practiceCharacter: 'Practice character',
      strokeProgress: (current, total) => `Stroke ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('en')} done`,
      mistakes: (count) => `${count.toLocaleString('en')} mistakes`,
      characters: (completed, total) => `${completed.toLocaleString('en')} / ${total.toLocaleString('en')} characters`,
    },
    resetDialog: {
      kicker: 'Reset progress',
      title: 'Saved work will be gone',
      description: (label) =>
        `Resetting ${label} will permanently remove your saved Known and Review marks for this study set, including words hidden by search or filters.`,
      summary: (label) => `${label} saved progress summary`,
      known: 'Known',
      review: 'Review',
      wordsAffected: 'Words affected',
      note: 'This cannot be undone.',
      keepProgress: 'Keep progress',
      resetProgress: 'Reset progress',
    },
    speech: {
      audioUnavailable: 'Audio playback is not available in this browser.',
      noMandarinVoice: 'No Mandarin voice is installed, so your browser will use its default voice.',
      customAudioFallbackUnavailable: 'Custom audio could not play, and speech synthesis is not available in this browser.',
      usingBrowserFallbackAudio: 'Using browser fallback audio.',
      usingBrowserAudio: 'Using browser audio.',
      audioCouldNotPlay: (error) => `Audio could not play: ${error}.`,
    },
  },
  es: {
    htmlLang: 'es',
    direction: 'ltr',
    allHsk: 'Todo HSK',
    classicMaps: 'Mapas clásicos de palabras HSK 1-6',
    allOverview: 'Vista general de niveles HSK',
    tileMap: (label) => `Mapa de fichas ${label}`,
    words: (count) => `${count.toLocaleString('es')} palabras`,
    newWords: (count) => `${count.toLocaleString('es')} palabras nuevas`,
    shown: (visible, total) => `${visible.toLocaleString('es')} / ${total.toLocaleString('es')} visibles`,
    filters: { all: 'Todo', learning: 'Repasar', know: 'Sabidas', unmarked: 'Sin marcar' },
    promptModes: { chinese: 'Chino primero', translation: 'Traducción primero' },
    searchLabel: 'Buscar',
    searchPlaceholder: 'Chino, pinyin o traducción',
    reset: 'Restablecer',
    known: 'Sabidas',
    review: 'Repasar',
    unmarked: 'Sin marcar',
    progressSummary: 'Resumen de progreso',
    mapControls: 'Controles del mapa',
    menuLabel: 'Menú',
    hskLevel: 'Nivel HSK',
    progressFilter: 'Filtro de progreso',
    flashcardPromptSide: 'Lado inicial de la tarjeta',
    translationLanguage: 'Idioma de traducción',
    showTranslationsIn: (language) => `Mostrar traducciones en ${language}`,
    allHskOverview: 'Vista general de todos los niveles HSK',
    levelProgress: (level) => `Progreso HSK ${level}`,
    matchingWords: (level) => `Palabras coincidentes HSK ${level}`,
    wordMap: (label) => `Mapa de palabras ${label}`,
    scrollableWordMap: (label) => `Mapa desplazable de palabras ${label}`,
    canvasWordMap: (label) => `Mapa canvas de palabras ${label}`,
    wordList: (label) => `Lista de palabras ${label}`,
    wordRange: (label, start, end) => `${label} palabras ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('es')} / ${total.toLocaleString('es')} visibles`,
    levelKnown: (count) => `${count.toLocaleString('es')} sabidas`,
    levelLearning: (count) => `${count.toLocaleString('es')} en repaso`,
    levelUnmarked: (count) => `${count.toLocaleString('es')} sin marcar`,
    noMatchesInLevel: 'No hay coincidencias en este nivel.',
    noWordsMatch: 'No hay palabras que coincidan con esta vista.',
    tryDifferentSearch: 'Prueba otra búsqueda o filtro de progreso.',
    closeDetails: 'Cerrar detalles',
    hskWord: (level) => `Palabra HSK ${level}`,
    revealChinese: 'Mostrar chino',
    revealAnswer: 'Mostrar respuesta',
    hideAnswer: 'Ocultar respuesta',
    unlockWriting: 'Muestra el chino para desbloquear la práctica de escritura',
    unlockExample: 'Muestra el chino para desbloquear el ejemplo',
    exampleSentence: 'Oración de ejemplo',
    showPinyin: 'Mostrar pinyin',
    hidePinyin: 'Ocultar pinyin',
    playAudio: 'Reproducir audio',
    reviewAgain: 'Repasar otra vez',
    iKnowThis: 'Ya la sé',
    clear: 'Borrar',
    writing: {
      strokeOrder: 'Orden de trazos',
      writingMode: 'Modo de escritura',
      watch: 'Ver',
      practice: 'Practicar',
      recall: 'Comprobar',
      writePrompt: 'Escribe',
      replay: 'Repetir',
      reset: 'Reiniciar',
      hint: 'Pista',
      writeCharacter: (character) => `Escribe ${character}`,
      strokeDataError: 'No se pudieron cargar los datos de trazos para este carácter.',
      tryStrokeAgain: 'Intenta ese trazo de nuevo',
      goodStroke: 'Buen trazo',
      characterComplete: (character) => `${character} completado`,
      wordComplete: 'Palabra completada',
      strokeOrderAnimation: (hanzi) => `Animación del orden de trazos para ${hanzi}`,
      animatedStrokeOrder: (character) => `Orden de trazos animado para ${character}`,
      characterStep: (current, total) => `Carácter ${current} / ${total}`,
      practiceWriting: (character) => `Practicar escritura de ${character}`,
      practiceCharacter: 'Practicar carácter',
      strokeProgress: (current, total) => `Trazo ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('es')} hechos`,
      mistakes: (count) => `${count.toLocaleString('es')} errores`,
      characters: (completed, total) => `${completed.toLocaleString('es')} / ${total.toLocaleString('es')} caracteres`,
    },
    resetDialog: {
      kicker: 'Restablecer progreso',
      title: 'Se perderá el trabajo guardado',
      description: (label) =>
        `Restablecer ${label} eliminará permanentemente tus marcas guardadas de Sabidas y Repasar para este conjunto, incluidas las palabras ocultas por búsqueda o filtros.`,
      summary: (label) => `Resumen de progreso guardado de ${label}`,
      known: 'Sabidas',
      review: 'Repasar',
      wordsAffected: 'Palabras afectadas',
      note: 'Esto no se puede deshacer.',
      keepProgress: 'Conservar progreso',
      resetProgress: 'Restablecer progreso',
    },
    speech: {
      audioUnavailable: 'La reproducción de audio no está disponible en este navegador.',
      noMandarinVoice: 'No hay una voz de mandarín instalada, así que el navegador usará su voz predeterminada.',
      customAudioFallbackUnavailable: 'El audio personalizado no se pudo reproducir y la síntesis de voz no está disponible en este navegador.',
      usingBrowserFallbackAudio: 'Usando audio alternativo del navegador.',
      usingBrowserAudio: 'Usando audio del navegador.',
      audioCouldNotPlay: (error) => `No se pudo reproducir el audio: ${error}.`,
    },
  },
  fr: {
    htmlLang: 'fr',
    direction: 'ltr',
    allHsk: 'Tout le HSK',
    classicMaps: 'Cartes classiques des mots HSK 1-6',
    allOverview: 'Vue d’ensemble des niveaux HSK',
    tileMap: (label) => `Carte en tuiles ${label}`,
    words: (count) => `${count.toLocaleString('fr')} mots`,
    newWords: (count) => `${count.toLocaleString('fr')} nouveaux mots`,
    shown: (visible, total) => `${visible.toLocaleString('fr')} / ${total.toLocaleString('fr')} affichés`,
    filters: { all: 'Tout', learning: 'Réviser', know: 'Connus', unmarked: 'Non marqués' },
    promptModes: { chinese: 'Chinois d’abord', translation: 'Traduction d’abord' },
    searchLabel: 'Rechercher',
    searchPlaceholder: 'Chinois, pinyin ou traduction',
    reset: 'Réinitialiser',
    known: 'Connus',
    review: 'Réviser',
    unmarked: 'Non marqués',
    progressSummary: 'Résumé de progression',
    mapControls: 'Contrôles de la carte',
    menuLabel: 'Menu',
    hskLevel: 'Niveau HSK',
    progressFilter: 'Filtre de progression',
    flashcardPromptSide: 'Face initiale de la carte',
    translationLanguage: 'Langue de traduction',
    showTranslationsIn: (language) => `Afficher les traductions en ${language}`,
    allHskOverview: 'Vue d’ensemble de tous les niveaux HSK',
    levelProgress: (level) => `Progression HSK ${level}`,
    matchingWords: (level) => `Mots correspondants HSK ${level}`,
    wordMap: (label) => `Carte de mots ${label}`,
    scrollableWordMap: (label) => `Carte de mots défilante ${label}`,
    canvasWordMap: (label) => `Carte de mots canvas ${label}`,
    wordList: (label) => `Liste de mots ${label}`,
    wordRange: (label, start, end) => `${label} mots ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('fr')} / ${total.toLocaleString('fr')} affichés`,
    levelKnown: (count) => `${count.toLocaleString('fr')} connus`,
    levelLearning: (count) => `${count.toLocaleString('fr')} à réviser`,
    levelUnmarked: (count) => `${count.toLocaleString('fr')} non marqués`,
    noMatchesInLevel: 'Aucune correspondance dans ce niveau.',
    noWordsMatch: 'Aucun mot ne correspond à cette vue.',
    tryDifferentSearch: 'Essayez une autre recherche ou un autre filtre de progression.',
    closeDetails: 'Fermer les détails',
    hskWord: (level) => `Mot HSK ${level}`,
    revealChinese: 'Afficher le chinois',
    revealAnswer: 'Afficher la réponse',
    hideAnswer: 'Masquer la réponse',
    unlockWriting: 'Affichez le chinois pour débloquer la pratique d’écriture',
    unlockExample: 'Affichez le chinois pour débloquer l’exemple',
    exampleSentence: 'Phrase d’exemple',
    showPinyin: 'Afficher le pinyin',
    hidePinyin: 'Masquer le pinyin',
    playAudio: 'Lire l’audio',
    reviewAgain: 'Réviser encore',
    iKnowThis: 'Je connais',
    clear: 'Effacer',
    writing: {
      strokeOrder: 'Ordre des traits',
      writingMode: 'Mode d’écriture',
      watch: 'Voir',
      practice: 'Pratiquer',
      recall: 'Tester',
      writePrompt: 'Écrivez',
      replay: 'Rejouer',
      reset: 'Réinitialiser',
      hint: 'Indice',
      writeCharacter: (character) => `Écrivez ${character}`,
      strokeDataError: 'Les données de traits n’ont pas pu être chargées pour ce caractère.',
      tryStrokeAgain: 'Essayez encore ce trait',
      goodStroke: 'Bon trait',
      characterComplete: (character) => `${character} terminé`,
      wordComplete: 'Mot terminé',
      strokeOrderAnimation: (hanzi) => `Animation de l’ordre des traits pour ${hanzi}`,
      animatedStrokeOrder: (character) => `Ordre des traits animé pour ${character}`,
      characterStep: (current, total) => `Caractère ${current} / ${total}`,
      practiceWriting: (character) => `Pratiquer l’écriture de ${character}`,
      practiceCharacter: 'Pratiquer le caractère',
      strokeProgress: (current, total) => `Trait ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('fr')} faits`,
      mistakes: (count) => `${count.toLocaleString('fr')} erreurs`,
      characters: (completed, total) => `${completed.toLocaleString('fr')} / ${total.toLocaleString('fr')} caractères`,
    },
    resetDialog: {
      kicker: 'Réinitialiser la progression',
      title: 'Le travail enregistré sera perdu',
      description: (label) =>
        `Réinitialiser ${label} supprimera définitivement vos marques Connus et Réviser pour cet ensemble, y compris les mots masqués par la recherche ou les filtres.`,
      summary: (label) => `Résumé de la progression enregistrée pour ${label}`,
      known: 'Connus',
      review: 'Réviser',
      wordsAffected: 'Mots concernés',
      note: 'Cette action est irréversible.',
      keepProgress: 'Garder la progression',
      resetProgress: 'Réinitialiser',
    },
    speech: {
      audioUnavailable: 'La lecture audio n’est pas disponible dans ce navigateur.',
      noMandarinVoice: 'Aucune voix mandarin n’est installée, le navigateur utilisera donc sa voix par défaut.',
      customAudioFallbackUnavailable: 'L’audio personnalisé n’a pas pu être lu et la synthèse vocale n’est pas disponible dans ce navigateur.',
      usingBrowserFallbackAudio: 'Utilisation de l’audio de secours du navigateur.',
      usingBrowserAudio: 'Utilisation de l’audio du navigateur.',
      audioCouldNotPlay: (error) => `Impossible de lire l’audio : ${error}.`,
    },
  },
  ru: {
    htmlLang: 'ru',
    direction: 'ltr',
    allHsk: 'Весь HSK',
    classicMaps: 'Классические карты слов HSK 1-6',
    allOverview: 'Обзор всех уровней HSK',
    tileMap: (label) => `Карта плиток ${label}`,
    words: (count) => `${count.toLocaleString('ru')} слов`,
    newWords: (count) => `${count.toLocaleString('ru')} новых слов`,
    shown: (visible, total) => `${visible.toLocaleString('ru')} / ${total.toLocaleString('ru')} показано`,
    filters: { all: 'Все', learning: 'Повторить', know: 'Знаю', unmarked: 'Без метки' },
    promptModes: { chinese: 'Сначала китайский', translation: 'Сначала перевод' },
    searchLabel: 'Поиск',
    searchPlaceholder: 'Китайский, пиньинь или перевод',
    reset: 'Сброс',
    known: 'Знаю',
    review: 'Повторить',
    unmarked: 'Без метки',
    progressSummary: 'Сводка прогресса',
    mapControls: 'Управление картой',
    menuLabel: 'Меню',
    hskLevel: 'Уровень HSK',
    progressFilter: 'Фильтр прогресса',
    flashcardPromptSide: 'Первая сторона карточки',
    translationLanguage: 'Язык перевода',
    showTranslationsIn: (language) => `Показывать переводы на ${language}`,
    allHskOverview: 'Обзор всех уровней HSK',
    levelProgress: (level) => `Прогресс HSK ${level}`,
    matchingWords: (level) => `Подходящие слова HSK ${level}`,
    wordMap: (label) => `Карта слов ${label}`,
    scrollableWordMap: (label) => `Прокручиваемая карта слов ${label}`,
    canvasWordMap: (label) => `Canvas-карта слов ${label}`,
    wordList: (label) => `Список слов ${label}`,
    wordRange: (label, start, end) => `${label}: слова ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('ru')} / ${total.toLocaleString('ru')} показано`,
    levelKnown: (count) => `${count.toLocaleString('ru')} знаю`,
    levelLearning: (count) => `${count.toLocaleString('ru')} на повторении`,
    levelUnmarked: (count) => `${count.toLocaleString('ru')} без метки`,
    noMatchesInLevel: 'На этом уровне совпадений нет.',
    noWordsMatch: 'Нет слов, подходящих к этой вкладке.',
    tryDifferentSearch: 'Попробуйте другой поиск или фильтр прогресса.',
    closeDetails: 'Закрыть подробности',
    hskWord: (level) => `Слово HSK ${level}`,
    revealChinese: 'Показать китайский',
    revealAnswer: 'Показать ответ',
    hideAnswer: 'Скрыть ответ',
    unlockWriting: 'Покажите китайский, чтобы открыть практику письма',
    unlockExample: 'Покажите китайский, чтобы открыть пример',
    exampleSentence: 'Пример предложения',
    showPinyin: 'Показать пиньинь',
    hidePinyin: 'Скрыть пиньинь',
    playAudio: 'Воспроизвести аудио',
    reviewAgain: 'Повторить снова',
    iKnowThis: 'Я знаю',
    clear: 'Очистить',
    writing: {
      strokeOrder: 'Порядок черт',
      writingMode: 'Режим письма',
      watch: 'Смотреть',
      practice: 'Практика',
      recall: 'Проверка',
      writePrompt: 'Напишите',
      replay: 'Повтор',
      reset: 'Сброс',
      hint: 'Подсказка',
      writeCharacter: (character) => `Напишите ${character}`,
      strokeDataError: 'Не удалось загрузить данные черт для этого иероглифа.',
      tryStrokeAgain: 'Попробуйте эту черту еще раз',
      goodStroke: 'Хорошая черта',
      characterComplete: (character) => `${character} завершен`,
      wordComplete: 'Слово завершено',
      strokeOrderAnimation: (hanzi) => `Анимация порядка черт для ${hanzi}`,
      animatedStrokeOrder: (character) => `Анимированный порядок черт для ${character}`,
      characterStep: (current, total) => `Иероглиф ${current} / ${total}`,
      practiceWriting: (character) => `Практика письма ${character}`,
      practiceCharacter: 'Практиковать иероглиф',
      strokeProgress: (current, total) => `Черта ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('ru')} выполнено`,
      mistakes: (count) => `${count.toLocaleString('ru')} ошибок`,
      characters: (completed, total) => `${completed.toLocaleString('ru')} / ${total.toLocaleString('ru')} иероглифов`,
    },
    resetDialog: {
      kicker: 'Сброс прогресса',
      title: 'Сохраненная работа будет удалена',
      description: (label) =>
        `Сброс ${label} навсегда удалит сохраненные отметки Знаю и Повторить для этого набора, включая слова, скрытые поиском или фильтрами.`,
      summary: (label) => `Сводка сохраненного прогресса ${label}`,
      known: 'Знаю',
      review: 'Повторить',
      wordsAffected: 'Затронуто слов',
      note: 'Это действие нельзя отменить.',
      keepProgress: 'Сохранить прогресс',
      resetProgress: 'Сбросить прогресс',
    },
    speech: {
      audioUnavailable: 'В этом браузере воспроизведение аудио недоступно.',
      noMandarinVoice: 'Голос мандаринского китайского не установлен, поэтому браузер использует голос по умолчанию.',
      customAudioFallbackUnavailable: 'Пользовательское аудио не воспроизвелось, а синтез речи недоступен в этом браузере.',
      usingBrowserFallbackAudio: 'Используется резервное аудио браузера.',
      usingBrowserAudio: 'Используется аудио браузера.',
      audioCouldNotPlay: (error) => `Не удалось воспроизвести аудио: ${error}.`,
    },
  },
  'pt-BR': {
    htmlLang: 'pt-BR',
    direction: 'ltr',
    allHsk: 'Todo HSK',
    classicMaps: 'Mapas clássicos de palavras HSK 1-6',
    allOverview: 'Visão geral dos níveis HSK',
    tileMap: (label) => `Mapa de blocos ${label}`,
    words: (count) => `${count.toLocaleString('pt-BR')} palavras`,
    newWords: (count) => `${count.toLocaleString('pt-BR')} palavras novas`,
    shown: (visible, total) => `${visible.toLocaleString('pt-BR')} / ${total.toLocaleString('pt-BR')} exibidas`,
    filters: { all: 'Todas', learning: 'Revisar', know: 'Conhecidas', unmarked: 'Sem marca' },
    promptModes: { chinese: 'Chinês primeiro', translation: 'Tradução primeiro' },
    searchLabel: 'Buscar',
    searchPlaceholder: 'Chinês, pinyin ou tradução',
    reset: 'Redefinir',
    known: 'Conhecidas',
    review: 'Revisar',
    unmarked: 'Sem marca',
    progressSummary: 'Resumo do progresso',
    mapControls: 'Controles do mapa',
    menuLabel: 'Menu',
    hskLevel: 'Nível HSK',
    progressFilter: 'Filtro de progresso',
    flashcardPromptSide: 'Lado inicial do cartão',
    translationLanguage: 'Idioma da tradução',
    showTranslationsIn: (language) => `Mostrar traduções em ${language}`,
    allHskOverview: 'Visão geral de todos os níveis HSK',
    levelProgress: (level) => `Progresso HSK ${level}`,
    matchingWords: (level) => `Palavras correspondentes HSK ${level}`,
    wordMap: (label) => `Mapa de palavras ${label}`,
    scrollableWordMap: (label) => `Mapa rolável de palavras ${label}`,
    canvasWordMap: (label) => `Mapa canvas de palavras ${label}`,
    wordList: (label) => `Lista de palavras ${label}`,
    wordRange: (label, start, end) => `${label} palavras ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('pt-BR')} / ${total.toLocaleString('pt-BR')} exibidas`,
    levelKnown: (count) => `${count.toLocaleString('pt-BR')} conhecidas`,
    levelLearning: (count) => `${count.toLocaleString('pt-BR')} em revisão`,
    levelUnmarked: (count) => `${count.toLocaleString('pt-BR')} sem marca`,
    noMatchesInLevel: 'Nenhuma correspondência neste nível.',
    noWordsMatch: 'Nenhuma palavra corresponde a esta visualização.',
    tryDifferentSearch: 'Tente outra busca ou filtro de progresso.',
    closeDetails: 'Fechar detalhes',
    hskWord: (level) => `Palavra HSK ${level}`,
    revealChinese: 'Mostrar chinês',
    revealAnswer: 'Mostrar resposta',
    hideAnswer: 'Ocultar resposta',
    unlockWriting: 'Mostre o chinês para desbloquear a prática de escrita',
    unlockExample: 'Mostre o chinês para desbloquear o exemplo',
    exampleSentence: 'Frase de exemplo',
    showPinyin: 'Mostrar pinyin',
    hidePinyin: 'Ocultar pinyin',
    playAudio: 'Reproduzir áudio',
    reviewAgain: 'Revisar novamente',
    iKnowThis: 'Eu sei isto',
    clear: 'Limpar',
    writing: {
      strokeOrder: 'Ordem dos traços',
      writingMode: 'Modo de escrita',
      watch: 'Assistir',
      practice: 'Praticar',
      recall: 'Testar',
      writePrompt: 'Escreva',
      replay: 'Repetir',
      reset: 'Reiniciar',
      hint: 'Dica',
      writeCharacter: (character) => `Escreva ${character}`,
      strokeDataError: 'Não foi possível carregar os dados dos traços deste caractere.',
      tryStrokeAgain: 'Tente esse traço novamente',
      goodStroke: 'Bom traço',
      characterComplete: (character) => `${character} concluído`,
      wordComplete: 'Palavra concluída',
      strokeOrderAnimation: (hanzi) => `Animação da ordem dos traços para ${hanzi}`,
      animatedStrokeOrder: (character) => `Ordem dos traços animada para ${character}`,
      characterStep: (current, total) => `Caractere ${current} / ${total}`,
      practiceWriting: (character) => `Praticar escrita de ${character}`,
      practiceCharacter: 'Praticar caractere',
      strokeProgress: (current, total) => `Traço ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('pt-BR')} feitos`,
      mistakes: (count) => `${count.toLocaleString('pt-BR')} erros`,
      characters: (completed, total) => `${completed.toLocaleString('pt-BR')} / ${total.toLocaleString('pt-BR')} caracteres`,
    },
    resetDialog: {
      kicker: 'Redefinir progresso',
      title: 'O trabalho salvo será perdido',
      description: (label) =>
        `Redefinir ${label} removerá permanentemente suas marcas salvas de Conhecidas e Revisar para este conjunto, incluindo palavras ocultas por busca ou filtros.`,
      summary: (label) => `Resumo do progresso salvo de ${label}`,
      known: 'Conhecidas',
      review: 'Revisar',
      wordsAffected: 'Palavras afetadas',
      note: 'Isto não pode ser desfeito.',
      keepProgress: 'Manter progresso',
      resetProgress: 'Redefinir progresso',
    },
    speech: {
      audioUnavailable: 'A reprodução de áudio não está disponível neste navegador.',
      noMandarinVoice: 'Nenhuma voz de mandarim está instalada, então o navegador usará a voz padrão.',
      customAudioFallbackUnavailable: 'O áudio personalizado não pôde ser reproduzido e a síntese de fala não está disponível neste navegador.',
      usingBrowserFallbackAudio: 'Usando áudio alternativo do navegador.',
      usingBrowserAudio: 'Usando áudio do navegador.',
      audioCouldNotPlay: (error) => `Não foi possível reproduzir o áudio: ${error}.`,
    },
  },
  de: {
    htmlLang: 'de',
    direction: 'ltr',
    allHsk: 'Alle HSK',
    classicMaps: 'Klassische HSK-1-6-Wortkarten',
    allOverview: 'Übersicht aller HSK-Stufen',
    tileMap: (label) => `${label} Kachelkarte`,
    words: (count) => `${count.toLocaleString('de')} Wörter`,
    newWords: (count) => `${count.toLocaleString('de')} neue Wörter`,
    shown: (visible, total) => `${visible.toLocaleString('de')} / ${total.toLocaleString('de')} angezeigt`,
    filters: { all: 'Alle', learning: 'Wiederholen', know: 'Bekannt', unmarked: 'Unmarkiert' },
    promptModes: { chinese: 'Chinesisch zuerst', translation: 'Übersetzung zuerst' },
    searchLabel: 'Suche',
    searchPlaceholder: 'Chinesisch, Pinyin oder Übersetzung',
    reset: 'Zurücksetzen',
    known: 'Bekannt',
    review: 'Wiederholen',
    unmarked: 'Unmarkiert',
    progressSummary: 'Fortschrittsübersicht',
    mapControls: 'Kartensteuerung',
    menuLabel: 'Menü',
    hskLevel: 'HSK-Stufe',
    progressFilter: 'Fortschrittsfilter',
    flashcardPromptSide: 'Startseite der Karte',
    translationLanguage: 'Übersetzungssprache',
    showTranslationsIn: (language) => `Übersetzungen auf ${language} anzeigen`,
    allHskOverview: 'Übersicht über alle HSK-Stufen',
    levelProgress: (level) => `Fortschritt HSK ${level}`,
    matchingWords: (level) => `Passende Wörter HSK ${level}`,
    wordMap: (label) => `${label} Wortkarte`,
    scrollableWordMap: (label) => `${label} scrollbare Wortkarte`,
    canvasWordMap: (label) => `${label} Canvas-Wortkarte`,
    wordList: (label) => `${label} Wortliste`,
    wordRange: (label, start, end) => `${label} Wörter ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('de')} / ${total.toLocaleString('de')} angezeigt`,
    levelKnown: (count) => `${count.toLocaleString('de')} bekannt`,
    levelLearning: (count) => `${count.toLocaleString('de')} in Wiederholung`,
    levelUnmarked: (count) => `${count.toLocaleString('de')} unmarkiert`,
    noMatchesInLevel: 'Keine Treffer in dieser Stufe.',
    noWordsMatch: 'Keine Wörter passen zu dieser Ansicht.',
    tryDifferentSearch: 'Versuche eine andere Suche oder einen anderen Fortschrittsfilter.',
    closeDetails: 'Details schließen',
    hskWord: (level) => `HSK-${level}-Wort`,
    revealChinese: 'Chinesisch anzeigen',
    revealAnswer: 'Antwort anzeigen',
    hideAnswer: 'Antwort ausblenden',
    unlockWriting: 'Chinesisch anzeigen, um die Schreibübung freizuschalten',
    unlockExample: 'Chinesisch anzeigen, um das Beispiel freizuschalten',
    exampleSentence: 'Beispielsatz',
    showPinyin: 'Pinyin anzeigen',
    hidePinyin: 'Pinyin ausblenden',
    playAudio: 'Audio abspielen',
    reviewAgain: 'Erneut wiederholen',
    iKnowThis: 'Ich weiß es',
    clear: 'Löschen',
    writing: {
      strokeOrder: 'Strichfolge',
      writingMode: 'Schreibmodus',
      watch: 'Ansehen',
      practice: 'Üben',
      recall: 'Testen',
      writePrompt: 'Schreiben',
      replay: 'Wiederholen',
      reset: 'Neu starten',
      hint: 'Hinweis',
      writeCharacter: (character) => `${character} schreiben`,
      strokeDataError: 'Strichdaten konnten für dieses Zeichen nicht geladen werden.',
      tryStrokeAgain: 'Versuche diesen Strich erneut',
      goodStroke: 'Guter Strich',
      characterComplete: (character) => `${character} abgeschlossen`,
      wordComplete: 'Wort abgeschlossen',
      strokeOrderAnimation: (hanzi) => `Strichfolge-Animation für ${hanzi}`,
      animatedStrokeOrder: (character) => `Animierte Strichfolge für ${character}`,
      characterStep: (current, total) => `Zeichen ${current} / ${total}`,
      practiceWriting: (character) => `${character} schreiben üben`,
      practiceCharacter: 'Zeichen üben',
      strokeProgress: (current, total) => `Strich ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('de')} erledigt`,
      mistakes: (count) => `${count.toLocaleString('de')} Fehler`,
      characters: (completed, total) => `${completed.toLocaleString('de')} / ${total.toLocaleString('de')} Zeichen`,
    },
    resetDialog: {
      kicker: 'Fortschritt zurücksetzen',
      title: 'Gespeicherte Arbeit geht verloren',
      description: (label) =>
        `Das Zurücksetzen von ${label} entfernt dauerhaft deine gespeicherten Markierungen Bekannt und Wiederholen für dieses Set, einschließlich durch Suche oder Filter ausgeblendeter Wörter.`,
      summary: (label) => `Zusammenfassung des gespeicherten Fortschritts für ${label}`,
      known: 'Bekannt',
      review: 'Wiederholen',
      wordsAffected: 'Betroffene Wörter',
      note: 'Dies kann nicht rückgängig gemacht werden.',
      keepProgress: 'Fortschritt behalten',
      resetProgress: 'Fortschritt zurücksetzen',
    },
    speech: {
      audioUnavailable: 'Audiowiedergabe ist in diesem Browser nicht verfügbar.',
      noMandarinVoice: 'Es ist keine Mandarin-Stimme installiert, daher verwendet der Browser seine Standardstimme.',
      customAudioFallbackUnavailable: 'Benutzerdefiniertes Audio konnte nicht abgespielt werden und Sprachsynthese ist in diesem Browser nicht verfügbar.',
      usingBrowserFallbackAudio: 'Browser-Ersatzaudio wird verwendet.',
      usingBrowserAudio: 'Browser-Audio wird verwendet.',
      audioCouldNotPlay: (error) => `Audio konnte nicht abgespielt werden: ${error}.`,
    },
  },
  ja: {
    htmlLang: 'ja',
    direction: 'ltr',
    allHsk: 'すべてのHSK',
    classicMaps: 'HSK 1-6 クラシック単語マップ',
    allOverview: 'HSKレベル全体',
    tileMap: (label) => `${label} タイルマップ`,
    words: (count) => `${count.toLocaleString('ja')}語`,
    newWords: (count) => `${count.toLocaleString('ja')}語の新出語`,
    shown: (visible, total) => `${visible.toLocaleString('ja')} / ${total.toLocaleString('ja')} 表示`,
    filters: { all: 'すべて', learning: '復習', know: '既知', unmarked: '未マーク' },
    promptModes: { chinese: '中国語から', translation: '翻訳から' },
    searchLabel: '検索',
    searchPlaceholder: '中国語、ピンイン、翻訳',
    reset: 'リセット',
    known: '既知',
    review: '復習',
    unmarked: '未マーク',
    progressSummary: '進捗サマリー',
    mapControls: 'マップ操作',
    menuLabel: 'メニュー',
    hskLevel: 'HSKレベル',
    progressFilter: '進捗フィルター',
    flashcardPromptSide: 'カードの開始面',
    translationLanguage: '翻訳言語',
    showTranslationsIn: (language) => `${language}で翻訳を表示`,
    allHskOverview: 'すべてのHSKレベルの概要',
    levelProgress: (level) => `HSK ${level} の進捗`,
    matchingWords: (level) => `HSK ${level} の一致単語`,
    wordMap: (label) => `${label} 単語マップ`,
    scrollableWordMap: (label) => `${label} スクロール可能な単語マップ`,
    canvasWordMap: (label) => `${label} canvas単語マップ`,
    wordList: (label) => `${label} 単語リスト`,
    wordRange: (label, start, end) => `${label} 単語 ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('ja')} / ${total.toLocaleString('ja')} 表示`,
    levelKnown: (count) => `${count.toLocaleString('ja')} 既知`,
    levelLearning: (count) => `${count.toLocaleString('ja')} 復習中`,
    levelUnmarked: (count) => `${count.toLocaleString('ja')} 未マーク`,
    noMatchesInLevel: 'このレベルに一致するものはありません。',
    noWordsMatch: 'この表示に一致する単語はありません。',
    tryDifferentSearch: '別の検索または進捗フィルターを試してください。',
    closeDetails: '詳細を閉じる',
    hskWord: (level) => `HSK ${level} 単語`,
    revealChinese: '中国語を表示',
    revealAnswer: '答えを表示',
    hideAnswer: '答えを隠す',
    unlockWriting: '中国語を表示すると書き取り練習が使えます',
    unlockExample: '中国語を表示すると例文が見られます',
    exampleSentence: '例文',
    showPinyin: 'ピンインを表示',
    hidePinyin: 'ピンインを隠す',
    playAudio: '音声を再生',
    reviewAgain: 'もう一度復習',
    iKnowThis: '覚えた',
    clear: 'クリア',
    writing: {
      strokeOrder: '筆順',
      writingMode: '書き取りモード',
      watch: '見る',
      practice: '練習',
      recall: '確認',
      writePrompt: '書く',
      replay: '再生',
      reset: 'リセット',
      hint: 'ヒント',
      writeCharacter: (character) => `${character} を書く`,
      strokeDataError: 'この文字の筆順データを読み込めませんでした。',
      tryStrokeAgain: 'その画をもう一度試してください',
      goodStroke: 'よい画です',
      characterComplete: (character) => `${character} 完了`,
      wordComplete: '単語完了',
      strokeOrderAnimation: (hanzi) => `${hanzi} の筆順アニメーション`,
      animatedStrokeOrder: (character) => `${character} の筆順アニメーション`,
      characterStep: (current, total) => `文字 ${current} / ${total}`,
      practiceWriting: (character) => `${character} の書き取り練習`,
      practiceCharacter: '文字を練習',
      strokeProgress: (current, total) => `画 ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('ja')} 完了`,
      mistakes: (count) => `${count.toLocaleString('ja')} ミス`,
      characters: (completed, total) => `${completed.toLocaleString('ja')} / ${total.toLocaleString('ja')} 文字`,
    },
    resetDialog: {
      kicker: '進捗をリセット',
      title: '保存済みの学習記録が削除されます',
      description: (label) =>
        `${label}をリセットすると、この学習セットの既知と復習の保存マークが完全に削除されます。検索やフィルターで隠れている単語も含まれます。`,
      summary: (label) => `${label} の保存済み進捗サマリー`,
      known: '既知',
      review: '復習',
      wordsAffected: '対象単語',
      note: 'この操作は元に戻せません。',
      keepProgress: '進捗を残す',
      resetProgress: '進捗をリセット',
    },
    speech: {
      audioUnavailable: 'このブラウザでは音声再生を利用できません。',
      noMandarinVoice: '中国語の音声がインストールされていないため、ブラウザの既定の音声を使用します。',
      customAudioFallbackUnavailable: 'カスタム音声を再生できず、このブラウザでは音声合成も利用できません。',
      usingBrowserFallbackAudio: 'ブラウザの代替音声を使用しています。',
      usingBrowserAudio: 'ブラウザ音声を使用しています。',
      audioCouldNotPlay: (error) => `音声を再生できませんでした: ${error}。`,
    },
  },
  ko: {
    htmlLang: 'ko',
    direction: 'ltr',
    allHsk: '전체 HSK',
    classicMaps: 'HSK 1-6 클래식 단어 지도',
    allOverview: '전체 HSK 레벨 개요',
    tileMap: (label) => `${label} 타일 지도`,
    words: (count) => `${count.toLocaleString('ko')}개 단어`,
    newWords: (count) => `${count.toLocaleString('ko')}개 새 단어`,
    shown: (visible, total) => `${visible.toLocaleString('ko')} / ${total.toLocaleString('ko')} 표시`,
    filters: { all: '전체', learning: '복습', know: '알고 있음', unmarked: '미표시' },
    promptModes: { chinese: '중국어 먼저', translation: '번역 먼저' },
    searchLabel: '검색',
    searchPlaceholder: '중국어, 병음 또는 번역',
    reset: '초기화',
    known: '알고 있음',
    review: '복습',
    unmarked: '미표시',
    progressSummary: '진도 요약',
    mapControls: '지도 컨트롤',
    menuLabel: '메뉴',
    hskLevel: 'HSK 레벨',
    progressFilter: '진도 필터',
    flashcardPromptSide: '카드 시작 면',
    translationLanguage: '번역 언어',
    showTranslationsIn: (language) => `${language} 번역 표시`,
    allHskOverview: '전체 HSK 레벨 개요',
    levelProgress: (level) => `HSK ${level} 진도`,
    matchingWords: (level) => `HSK ${level} 일치 단어`,
    wordMap: (label) => `${label} 단어 지도`,
    scrollableWordMap: (label) => `${label} 스크롤 단어 지도`,
    canvasWordMap: (label) => `${label} 캔버스 단어 지도`,
    wordList: (label) => `${label} 단어 목록`,
    wordRange: (label, start, end) => `${label} 단어 ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('ko')} / ${total.toLocaleString('ko')} 표시`,
    levelKnown: (count) => `${count.toLocaleString('ko')}개 알고 있음`,
    levelLearning: (count) => `${count.toLocaleString('ko')}개 복습 중`,
    levelUnmarked: (count) => `${count.toLocaleString('ko')}개 미표시`,
    noMatchesInLevel: '이 레벨에는 일치하는 단어가 없습니다.',
    noWordsMatch: '이 보기에 맞는 단어가 없습니다.',
    tryDifferentSearch: '다른 검색어나 진도 필터를 시도하세요.',
    closeDetails: '상세 닫기',
    hskWord: (level) => `HSK ${level} 단어`,
    revealChinese: '중국어 보기',
    revealAnswer: '답 보기',
    hideAnswer: '답 숨기기',
    unlockWriting: '중국어를 보면 쓰기 연습이 열립니다',
    unlockExample: '중국어를 보면 예문이 열립니다',
    exampleSentence: '예문',
    showPinyin: '병음 보기',
    hidePinyin: '병음 숨기기',
    playAudio: '오디오 재생',
    reviewAgain: '다시 복습',
    iKnowThis: '알고 있어요',
    clear: '지우기',
    writing: {
      strokeOrder: '획순',
      writingMode: '쓰기 모드',
      watch: '보기',
      practice: '연습',
      recall: '확인',
      writePrompt: '쓰기',
      replay: '다시 보기',
      reset: '초기화',
      hint: '힌트',
      writeCharacter: (character) => `${character} 쓰기`,
      strokeDataError: '이 글자의 획 데이터를 불러올 수 없습니다.',
      tryStrokeAgain: '그 획을 다시 시도하세요',
      goodStroke: '좋은 획입니다',
      characterComplete: (character) => `${character} 완료`,
      wordComplete: '단어 완료',
      strokeOrderAnimation: (hanzi) => `${hanzi} 획순 애니메이션`,
      animatedStrokeOrder: (character) => `${character} 획순 애니메이션`,
      characterStep: (current, total) => `글자 ${current} / ${total}`,
      practiceWriting: (character) => `${character} 쓰기 연습`,
      practiceCharacter: '글자 연습',
      strokeProgress: (current, total) => `획 ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('ko')}개 완료`,
      mistakes: (count) => `${count.toLocaleString('ko')}개 실수`,
      characters: (completed, total) => `${completed.toLocaleString('ko')} / ${total.toLocaleString('ko')} 글자`,
    },
    resetDialog: {
      kicker: '진도 초기화',
      title: '저장된 학습 기록이 삭제됩니다',
      description: (label) =>
        `${label}을 초기화하면 이 학습 세트의 알고 있음 및 복습 표시가 영구적으로 삭제됩니다. 검색이나 필터로 숨겨진 단어도 포함됩니다.`,
      summary: (label) => `${label} 저장된 진도 요약`,
      known: '알고 있음',
      review: '복습',
      wordsAffected: '영향받는 단어',
      note: '이 작업은 되돌릴 수 없습니다.',
      keepProgress: '진도 유지',
      resetProgress: '진도 초기화',
    },
    speech: {
      audioUnavailable: '이 브라우저에서는 오디오 재생을 사용할 수 없습니다.',
      noMandarinVoice: '중국어 음성이 설치되어 있지 않아 브라우저 기본 음성을 사용합니다.',
      customAudioFallbackUnavailable: '사용자 지정 오디오를 재생할 수 없고 이 브라우저에서 음성 합성을 사용할 수 없습니다.',
      usingBrowserFallbackAudio: '브라우저 대체 오디오를 사용 중입니다.',
      usingBrowserAudio: '브라우저 오디오를 사용 중입니다.',
      audioCouldNotPlay: (error) => `오디오를 재생할 수 없습니다: ${error}.`,
    },
  },
  vi: {
    htmlLang: 'vi',
    direction: 'ltr',
    allHsk: 'Tất cả HSK',
    classicMaps: 'Bản đồ từ HSK 1-6 cổ điển',
    allOverview: 'Tổng quan các cấp HSK',
    tileMap: (label) => `Bản đồ ô ${label}`,
    words: (count) => `${count.toLocaleString('vi')} từ`,
    newWords: (count) => `${count.toLocaleString('vi')} từ mới`,
    shown: (visible, total) => `${visible.toLocaleString('vi')} / ${total.toLocaleString('vi')} hiển thị`,
    filters: { all: 'Tất cả', learning: 'Ôn tập', know: 'Đã biết', unmarked: 'Chưa đánh dấu' },
    promptModes: { chinese: 'Tiếng Trung trước', translation: 'Bản dịch trước' },
    searchLabel: 'Tìm kiếm',
    searchPlaceholder: 'Tiếng Trung, pinyin hoặc bản dịch',
    reset: 'Đặt lại',
    known: 'Đã biết',
    review: 'Ôn tập',
    unmarked: 'Chưa đánh dấu',
    progressSummary: 'Tóm tắt tiến độ',
    mapControls: 'Điều khiển bản đồ',
    menuLabel: 'Trình đơn',
    hskLevel: 'Cấp HSK',
    progressFilter: 'Bộ lọc tiến độ',
    flashcardPromptSide: 'Mặt bắt đầu của thẻ',
    translationLanguage: 'Ngôn ngữ bản dịch',
    showTranslationsIn: (language) => `Hiển thị bản dịch bằng ${language}`,
    allHskOverview: 'Tổng quan tất cả cấp HSK',
    levelProgress: (level) => `Tiến độ HSK ${level}`,
    matchingWords: (level) => `Từ khớp HSK ${level}`,
    wordMap: (label) => `Bản đồ từ ${label}`,
    scrollableWordMap: (label) => `Bản đồ từ cuộn được ${label}`,
    canvasWordMap: (label) => `Bản đồ từ canvas ${label}`,
    wordList: (label) => `Danh sách từ ${label}`,
    wordRange: (label, start, end) => `${label} từ ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('vi')} / ${total.toLocaleString('vi')} hiển thị`,
    levelKnown: (count) => `${count.toLocaleString('vi')} đã biết`,
    levelLearning: (count) => `${count.toLocaleString('vi')} đang ôn`,
    levelUnmarked: (count) => `${count.toLocaleString('vi')} chưa đánh dấu`,
    noMatchesInLevel: 'Không có kết quả trong cấp này.',
    noWordsMatch: 'Không có từ nào khớp với chế độ xem này.',
    tryDifferentSearch: 'Thử tìm kiếm hoặc bộ lọc tiến độ khác.',
    closeDetails: 'Đóng chi tiết',
    hskWord: (level) => `Từ HSK ${level}`,
    revealChinese: 'Hiện tiếng Trung',
    revealAnswer: 'Hiện đáp án',
    hideAnswer: 'Ẩn đáp án',
    unlockWriting: 'Hiện tiếng Trung để mở luyện viết',
    unlockExample: 'Hiện tiếng Trung để mở ví dụ',
    exampleSentence: 'Câu ví dụ',
    showPinyin: 'Hiện pinyin',
    hidePinyin: 'Ẩn pinyin',
    playAudio: 'Phát âm thanh',
    reviewAgain: 'Ôn lại',
    iKnowThis: 'Tôi biết rồi',
    clear: 'Xóa',
    writing: {
      strokeOrder: 'Thứ tự nét',
      writingMode: 'Chế độ viết',
      watch: 'Xem',
      practice: 'Luyện tập',
      recall: 'Kiểm tra',
      writePrompt: 'Viết',
      replay: 'Phát lại',
      reset: 'Đặt lại',
      hint: 'Gợi ý',
      writeCharacter: (character) => `Viết ${character}`,
      strokeDataError: 'Không thể tải dữ liệu nét cho chữ này.',
      tryStrokeAgain: 'Thử lại nét đó',
      goodStroke: 'Nét tốt',
      characterComplete: (character) => `${character} hoàn thành`,
      wordComplete: 'Hoàn thành từ',
      strokeOrderAnimation: (hanzi) => `Hoạt ảnh thứ tự nét cho ${hanzi}`,
      animatedStrokeOrder: (character) => `Thứ tự nét hoạt ảnh cho ${character}`,
      characterStep: (current, total) => `Chữ ${current} / ${total}`,
      practiceWriting: (character) => `Luyện viết ${character}`,
      practiceCharacter: 'Luyện chữ',
      strokeProgress: (current, total) => `Nét ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('vi')} xong`,
      mistakes: (count) => `${count.toLocaleString('vi')} lỗi`,
      characters: (completed, total) => `${completed.toLocaleString('vi')} / ${total.toLocaleString('vi')} chữ`,
    },
    resetDialog: {
      kicker: 'Đặt lại tiến độ',
      title: 'Dữ liệu đã lưu sẽ bị mất',
      description: (label) =>
        `Đặt lại ${label} sẽ xóa vĩnh viễn các dấu Đã biết và Ôn tập đã lưu cho bộ học này, bao gồm cả các từ bị ẩn bởi tìm kiếm hoặc bộ lọc.`,
      summary: (label) => `Tóm tắt tiến độ đã lưu của ${label}`,
      known: 'Đã biết',
      review: 'Ôn tập',
      wordsAffected: 'Từ bị ảnh hưởng',
      note: 'Không thể hoàn tác thao tác này.',
      keepProgress: 'Giữ tiến độ',
      resetProgress: 'Đặt lại tiến độ',
    },
    speech: {
      audioUnavailable: 'Trình duyệt này không hỗ trợ phát âm thanh.',
      noMandarinVoice: 'Chưa cài giọng Quan thoại, nên trình duyệt sẽ dùng giọng mặc định.',
      customAudioFallbackUnavailable: 'Không phát được âm thanh tùy chỉnh và trình duyệt này không hỗ trợ tổng hợp giọng nói.',
      usingBrowserFallbackAudio: 'Đang dùng âm thanh dự phòng của trình duyệt.',
      usingBrowserAudio: 'Đang dùng âm thanh của trình duyệt.',
      audioCouldNotPlay: (error) => `Không thể phát âm thanh: ${error}.`,
    },
  },
  id: {
    htmlLang: 'id',
    direction: 'ltr',
    allHsk: 'Semua HSK',
    classicMaps: 'Peta kata klasik HSK 1-6',
    allOverview: 'Ringkasan semua level HSK',
    tileMap: (label) => `Peta ubin ${label}`,
    words: (count) => `${count.toLocaleString('id')} kata`,
    newWords: (count) => `${count.toLocaleString('id')} kata baru`,
    shown: (visible, total) => `${visible.toLocaleString('id')} / ${total.toLocaleString('id')} ditampilkan`,
    filters: { all: 'Semua', learning: 'Ulas', know: 'Sudah tahu', unmarked: 'Belum ditandai' },
    promptModes: { chinese: 'Mandarin dulu', translation: 'Terjemahan dulu' },
    searchLabel: 'Cari',
    searchPlaceholder: 'Mandarin, pinyin, atau terjemahan',
    reset: 'Atur ulang',
    known: 'Sudah tahu',
    review: 'Ulas',
    unmarked: 'Belum ditandai',
    progressSummary: 'Ringkasan progres',
    mapControls: 'Kontrol peta',
    menuLabel: 'Menu',
    hskLevel: 'Level HSK',
    progressFilter: 'Filter progres',
    flashcardPromptSide: 'Sisi awal kartu',
    translationLanguage: 'Bahasa terjemahan',
    showTranslationsIn: (language) => `Tampilkan terjemahan dalam ${language}`,
    allHskOverview: 'Ringkasan semua level HSK',
    levelProgress: (level) => `Progres HSK ${level}`,
    matchingWords: (level) => `Kata cocok HSK ${level}`,
    wordMap: (label) => `Peta kata ${label}`,
    scrollableWordMap: (label) => `Peta kata bergulir ${label}`,
    canvasWordMap: (label) => `Peta kata canvas ${label}`,
    wordList: (label) => `Daftar kata ${label}`,
    wordRange: (label, start, end) => `${label} kata ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('id')} / ${total.toLocaleString('id')} ditampilkan`,
    levelKnown: (count) => `${count.toLocaleString('id')} sudah tahu`,
    levelLearning: (count) => `${count.toLocaleString('id')} diulas`,
    levelUnmarked: (count) => `${count.toLocaleString('id')} belum ditandai`,
    noMatchesInLevel: 'Tidak ada kecocokan di level ini.',
    noWordsMatch: 'Tidak ada kata yang cocok dengan tampilan ini.',
    tryDifferentSearch: 'Coba pencarian atau filter progres lain.',
    closeDetails: 'Tutup detail',
    hskWord: (level) => `Kata HSK ${level}`,
    revealChinese: 'Tampilkan Mandarin',
    revealAnswer: 'Tampilkan jawaban',
    hideAnswer: 'Sembunyikan jawaban',
    unlockWriting: 'Tampilkan Mandarin untuk membuka latihan menulis',
    unlockExample: 'Tampilkan Mandarin untuk membuka contoh',
    exampleSentence: 'Contoh kalimat',
    showPinyin: 'Tampilkan pinyin',
    hidePinyin: 'Sembunyikan pinyin',
    playAudio: 'Putar audio',
    reviewAgain: 'Ulas lagi',
    iKnowThis: 'Saya tahu ini',
    clear: 'Hapus',
    writing: {
      strokeOrder: 'Urutan guratan',
      writingMode: 'Mode menulis',
      watch: 'Lihat',
      practice: 'Latihan',
      recall: 'Uji',
      writePrompt: 'Tulis',
      replay: 'Putar ulang',
      reset: 'Atur ulang',
      hint: 'Petunjuk',
      writeCharacter: (character) => `Tulis ${character}`,
      strokeDataError: 'Data guratan untuk karakter ini tidak dapat dimuat.',
      tryStrokeAgain: 'Coba guratan itu lagi',
      goodStroke: 'Guratan bagus',
      characterComplete: (character) => `${character} selesai`,
      wordComplete: 'Kata selesai',
      strokeOrderAnimation: (hanzi) => `Animasi urutan guratan untuk ${hanzi}`,
      animatedStrokeOrder: (character) => `Urutan guratan animasi untuk ${character}`,
      characterStep: (current, total) => `Karakter ${current} / ${total}`,
      practiceWriting: (character) => `Latihan menulis ${character}`,
      practiceCharacter: 'Latihan karakter',
      strokeProgress: (current, total) => `Guratan ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('id')} selesai`,
      mistakes: (count) => `${count.toLocaleString('id')} kesalahan`,
      characters: (completed, total) => `${completed.toLocaleString('id')} / ${total.toLocaleString('id')} karakter`,
    },
    resetDialog: {
      kicker: 'Atur ulang progres',
      title: 'Data tersimpan akan hilang',
      description: (label) =>
        `Mengatur ulang ${label} akan menghapus permanen tanda Sudah tahu dan Ulas untuk set belajar ini, termasuk kata yang disembunyikan oleh pencarian atau filter.`,
      summary: (label) => `Ringkasan progres tersimpan ${label}`,
      known: 'Sudah tahu',
      review: 'Ulas',
      wordsAffected: 'Kata terdampak',
      note: 'Ini tidak dapat dibatalkan.',
      keepProgress: 'Pertahankan progres',
      resetProgress: 'Atur ulang progres',
    },
    speech: {
      audioUnavailable: 'Pemutaran audio tidak tersedia di browser ini.',
      noMandarinVoice: 'Tidak ada suara Mandarin yang terpasang, jadi browser akan memakai suara default.',
      customAudioFallbackUnavailable: 'Audio kustom tidak dapat diputar dan sintesis suara tidak tersedia di browser ini.',
      usingBrowserFallbackAudio: 'Menggunakan audio cadangan browser.',
      usingBrowserAudio: 'Menggunakan audio browser.',
      audioCouldNotPlay: (error) => `Audio tidak dapat diputar: ${error}.`,
    },
  },
  ar: {
    htmlLang: 'ar',
    direction: 'rtl',
    allHsk: 'كل HSK',
    classicMaps: 'خرائط كلمات HSK 1-6 الكلاسيكية',
    allOverview: 'نظرة عامة على مستويات HSK',
    tileMap: (label) => `خريطة مربعات ${label}`,
    words: (count) => `${count.toLocaleString('ar')} كلمة`,
    newWords: (count) => `${count.toLocaleString('ar')} كلمة جديدة`,
    shown: (visible, total) => `${visible.toLocaleString('ar')} / ${total.toLocaleString('ar')} معروضة`,
    filters: { all: 'الكل', learning: 'مراجعة', know: 'معروفة', unmarked: 'غير محددة' },
    promptModes: { chinese: 'الصينية أولا', translation: 'الترجمة أولا' },
    searchLabel: 'بحث',
    searchPlaceholder: 'الصينية أو البينيين أو الترجمة',
    reset: 'إعادة ضبط',
    known: 'معروفة',
    review: 'مراجعة',
    unmarked: 'غير محددة',
    progressSummary: 'ملخص التقدم',
    mapControls: 'أدوات التحكم بالخريطة',
    menuLabel: 'القائمة',
    hskLevel: 'مستوى HSK',
    progressFilter: 'مرشح التقدم',
    flashcardPromptSide: 'وجه البطاقة الأول',
    translationLanguage: 'لغة الترجمة',
    showTranslationsIn: (language) => `عرض الترجمات باللغة ${language}`,
    allHskOverview: 'نظرة عامة على كل مستويات HSK',
    levelProgress: (level) => `تقدم HSK ${level}`,
    matchingWords: (level) => `كلمات مطابقة HSK ${level}`,
    wordMap: (label) => `خريطة كلمات ${label}`,
    scrollableWordMap: (label) => `خريطة كلمات قابلة للتمرير ${label}`,
    canvasWordMap: (label) => `خريطة كلمات canvas ${label}`,
    wordList: (label) => `قائمة كلمات ${label}`,
    wordRange: (label, start, end) => `${label} كلمات ${start}-${end}`,
    levelCardCount: (visible, total) => `${visible.toLocaleString('ar')} / ${total.toLocaleString('ar')} معروضة`,
    levelKnown: (count) => `${count.toLocaleString('ar')} معروفة`,
    levelLearning: (count) => `${count.toLocaleString('ar')} قيد المراجعة`,
    levelUnmarked: (count) => `${count.toLocaleString('ar')} غير محددة`,
    noMatchesInLevel: 'لا توجد نتائج في هذا المستوى.',
    noWordsMatch: 'لا توجد كلمات تطابق هذا العرض.',
    tryDifferentSearch: 'جرب بحثا مختلفا أو مرشح تقدم آخر.',
    closeDetails: 'إغلاق التفاصيل',
    hskWord: (level) => `كلمة HSK ${level}`,
    revealChinese: 'إظهار الصينية',
    revealAnswer: 'إظهار الإجابة',
    hideAnswer: 'إخفاء الإجابة',
    unlockWriting: 'أظهر الصينية لفتح تدريب الكتابة',
    unlockExample: 'أظهر الصينية لفتح المثال',
    exampleSentence: 'جملة مثال',
    showPinyin: 'إظهار البينيين',
    hidePinyin: 'إخفاء البينيين',
    playAudio: 'تشغيل الصوت',
    reviewAgain: 'راجع مرة أخرى',
    iKnowThis: 'أعرف هذه',
    clear: 'مسح',
    writing: {
      strokeOrder: 'ترتيب الخطوط',
      writingMode: 'وضع الكتابة',
      watch: 'مشاهدة',
      practice: 'تدريب',
      recall: 'اختبار',
      writePrompt: 'اكتب',
      replay: 'إعادة',
      reset: 'إعادة ضبط',
      hint: 'تلميح',
      writeCharacter: (character) => `اكتب ${character}`,
      strokeDataError: 'تعذر تحميل بيانات الخطوط لهذا الحرف.',
      tryStrokeAgain: 'جرب هذا الخط مرة أخرى',
      goodStroke: 'خط جيد',
      characterComplete: (character) => `اكتمل ${character}`,
      wordComplete: 'اكتملت الكلمة',
      strokeOrderAnimation: (hanzi) => `تحريك ترتيب الخطوط لـ ${hanzi}`,
      animatedStrokeOrder: (character) => `ترتيب خطوط متحرك لـ ${character}`,
      characterStep: (current, total) => `الحرف ${current} / ${total}`,
      practiceWriting: (character) => `تدرب على كتابة ${character}`,
      practiceCharacter: 'تدرب على الحرف',
      strokeProgress: (current, total) => `الخط ${current} / ${total}`,
      done: (count) => `${count.toLocaleString('ar')} منجزة`,
      mistakes: (count) => `${count.toLocaleString('ar')} أخطاء`,
      characters: (completed, total) => `${completed.toLocaleString('ar')} / ${total.toLocaleString('ar')} أحرف`,
    },
    resetDialog: {
      kicker: 'إعادة ضبط التقدم',
      title: 'سيتم حذف العمل المحفوظ',
      description: (label) =>
        `ستؤدي إعادة ضبط ${label} إلى حذف علامات معروفة ومراجعة المحفوظة نهائيا لهذه المجموعة، بما في ذلك الكلمات المخفية بالبحث أو المرشحات.`,
      summary: (label) => `ملخص التقدم المحفوظ لـ ${label}`,
      known: 'معروفة',
      review: 'مراجعة',
      wordsAffected: 'الكلمات المتأثرة',
      note: 'لا يمكن التراجع عن هذا.',
      keepProgress: 'الاحتفاظ بالتقدم',
      resetProgress: 'إعادة ضبط التقدم',
    },
    speech: {
      audioUnavailable: 'تشغيل الصوت غير متاح في هذا المتصفح.',
      noMandarinVoice: 'لا يوجد صوت الماندرين مثبت، لذلك سيستخدم المتصفح صوته الافتراضي.',
      customAudioFallbackUnavailable: 'تعذر تشغيل الصوت المخصص، كما أن تركيب الكلام غير متاح في هذا المتصفح.',
      usingBrowserFallbackAudio: 'استخدام صوت المتصفح الاحتياطي.',
      usingBrowserAudio: 'استخدام صوت المتصفح.',
      audioCouldNotPlay: (error) => `تعذر تشغيل الصوت: ${error}.`,
    },
  },
};

export function getUiCopy(language: TranslationLanguage) {
  return UI_COPY[language] ?? UI_COPY.en;
}
